>python -c "import sounddevice; print(sounddevice.query_devices())"
   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone Array (Intel® Smart , MME (2 in, 0 out)
   2 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  3 Speakers (Realtek(R) Audio), MME (0 in, 2 out)
   4 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   5 Microphone Array (Intel® Smart Sound Technology for Digital Microphones), Windows DirectSound (2 in, 0 out)
   6 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
   7 Speakers (Realtek(R) Audio), Windows DirectSound (0 in, 2 out)
   8 Speakers (Realtek(R) Audio), Windows WASAPI (0 in, 2 out)
   9 Microphone Array (Intel® Smart Sound Technology for Digital Microphones), Windows WASAPI (2 in, 0 out)
  10 Speakers (Nahimic mirroring Wave Speaker), Windows WDM-KS (0 in, 2 out)
  11 Headphones (Realtek HD Audio 2nd output with SST), Windows WDM-KS (0 in, 2 out)
  12 Speakers (Realtek HD Audio output with SST), Windows WDM-KS (0 in, 2 out)
  13 Stereo Mix (Realtek HD Audio Stereo input), Windows WDM-KS (2 in, 0 out)
  14 Microphone (Realtek HD Audio Mic input), Windows WDM-KS (2 in, 0 out)
  15 Speakers (Nahimic Easy Surround), Windows WDM-KS (0 in, 8 out)
  16 Microphone Array 1 (), Windows WDM-KS (2 in, 0 out)
  17 Microphone Array 2 (), Windows WDM-KS (2 in, 0 out)
  18 Microphone Array 3 (), Windows WDM-KS (4 in, 0 out)
  19 Microphone Array 4 (), Windows WDM-KS (4 in, 0 out)
